name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        php-version:
#          - "5.6"
#          - "7.4"
          - "8.4"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: "memory_limit=-1"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Run tests
        run: tools/phpunit
